version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      tracing:
        applies-to: "version-updates"
        patterns:
          - "tracing-*"
      crypto:
        applies-to: "version-updates"
        patterns:
          - "base64ct"
          - "der"
          - "digest"
          - "ecdsa"
          - "elliptic-curve"
          - "generic-array"
          - "hmac"
          - "p256"
          - "p384"
          - "p521"
          - "pkcs8"
          - "rand"
          - "rand_core"
          - "rsa"
          - "sha1"
          - "sha2"
          - "signature"
          - "spki"
          - "zeroize"
