on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  release:
    types: [published]

name: CI

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: rust cache
        uses: Swatinem/rust-cache@v2.0.0

      - name: Run cargo build
        run: cargo build --all-features --release

  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - ""
          - "--no-default-features --features rsa,ecdsa,p256,p384,p521"
          - "--no-default-features --features fmt"
          - "--no-default-features --features fmt,ecdsa,p256,p384,p521"
          - "--no-default-features --features fmt,rsa"
        toolchain:
          - stable
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: rust cache
        uses: Swatinem/rust-cache@v2.0.0

      - name: Build cargo tests
        run: cargo test --no-run ${{ matrix.features }}

      - name: Run cargo tests
        run: cargo test ${{ matrix.features }}

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt,clippy

      - name: rust cache
        uses: Swatinem/rust-cache@v2.0.0

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -D warnings

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rust-docs

      - name: rust cache
        uses: Swatinem/rust-cache@v2.0.0

      - name: cargo doc
        env:
          RUSTDOCFLAGS: "-Dwarnings"
        run: cargo doc --all-features --no-deps
